DJDevAlan/applications/Persona/urls.py
from django.urls import path
from . import views

app_name="persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(),
        name='inicio'
    ),
    path('Listar-todos-empleados/', views.LisAllEmpleados.as_view(), name='empleados_all'),
    path('lista-by-area/<subnombre>/', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('buscar-empleado/', views.listEmpleadoByKword.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadosDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'success/', 
        views.SuccessView.as_view(), 
        name='correcto'
    ),
    path(
        'update-empleado/<pk>', 
        views.EmpleadoUpdateView.as_view(), 
        name='Modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>', 
        views.EmpleadoDeleteView.as_view(), 
        name='Eliminar_Empleado'
    ),
    path(
        'lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(), 
        name='empleados_admin'
    ),
    path('habilidades/', views.ListaHabilidadesView.as_view(), name='lista_habilidades'),
    path('habilidad/add/', views.HabilidadCreateView.as_view(), name='add_habilidad'),
    path('habilidad/update/<pk>/', views.HabilidadUpdateView.as_view(), name='update_habilidad'),
    path('habilidad/delete/<pk>/', views.HabilidadDeleteView.as_view(), name='delete_habilidad'),
    
]

DJDevAlan/applications/departamento/urls.py
from django.contrib import admin 
from django.urls import path

from . import views
app_name='departamento_app'

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path('departamento-lista/',views.DepartamentoListView.as_view(), name='departamento-list'),
]

DJDevAlan/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.Persona.views import LisAllEmpleados
from django.conf.urls.static import static
from django.conf import settings
from applications.Persona.views import debug_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.Persona.urls')),
    path('', include('applications.departamento.urls')),
    path('', debug_view), 
    #path('listar-todos-empleados/', LisAllEmpleados.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DJDevAlan/templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li>
        <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
        <!--<ul class="menu vertical">
        </ul>-->
      </li>
      <li><a href="{% url 'departamento_app:departamento-list' %}">Departamentos</a></li>
      <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
      <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>
      <li>
        <a href="{% url 'persona_app:lista_habilidades' %}">Habilidades</a>
      </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar Empleado"></li>
      <a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar Nuevo</a>
    </ul>
  </div>
</div>