DJDevAlan/applications/Persona/urls.py
from django.urls import path
from . import views

app_name="persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(),
        name='inicio'
    ),
    path('Listar-todos-empleados/', views.LisAllEmpleados.as_view(), name='empleados_all'),
    path('lista-by-area/<subnombre>/', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('buscar-empleado/', views.listEmpleadoByKword.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadosDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'success/', 
        views.SuccessView.as_view(), 
        name='correcto'
    ),
    path(
        'update-empleado/<pk>', 
        views.EmpleadoUpdateView.as_view(), 
        name='Modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>', 
        views.EmpleadoDeleteView.as_view(), 
        name='Eliminar_Empleado'
    ),
    path(
        'lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(), 
        name='empleados_admin'
    ),
    path('habilidades/', views.ListaHabilidadesView.as_view(), name='lista_habilidades'),
    path('habilidad/add/', views.HabilidadCreateView.as_view(), name='add_habilidad'),
    path('habilidad/update/<pk>/', views.HabilidadUpdateView.as_view(), name='update_habilidad'),
    path('habilidad/delete/<pk>/', views.HabilidadDeleteView.as_view(), name='delete_habilidad'),
    
]

DJDevAlan/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.Persona.views import LisAllEmpleados
from django.conf.urls.static import static
from django.conf import settings
from applications.Persona.views import debug_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.Persona.urls')),
    path('', include('applications.departamento.urls')),
    path('', debug_view), 
    #path('listar-todos-empleados/', LisAllEmpleados.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DJDevAlan/applications/Persona/models.py
from django.db import models
from ckeditor.fields import RichTextField
from applications.departamento.models import Departamento

class Habilidades(models.Model):
    habilidad=models.CharField('Habilidad', max_length=50)
    
    class meta:
        verbose_name='Habilidades'
        verbose_name_plural='Habilidades empleados'
    
    def __str__(self):
        return str(self.id)+'-'+self.habilidad


class Empleado(models.Model):
    JOB_CHOICES=(
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )
    
    first_name=models.CharField('Nombre', max_length=60)
    last_name=models.CharField('Apellidos', max_length=60)
    full_name=models.CharField('Nombre completo', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    Habilidades=models.ManyToManyField(Habilidades)
    hoja_vida=RichTextField()
    
    class meta:
        verbose_name='Mi Empleado'
        verbose_name_plurarl='Empleados de la empresa'
        ordering=['-first_name','last_name']
        unique_together=('first_name', 'Departamento')
    
    def __str__(self):
        return str (self.id)+'-'+ self.first_name +'-'+ self.last_name

DJDevAlan/applications/Persona/forms.py
from .models import Empleado
from django import forms
from .models import Habilidades


class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'Habilidades',
        )
        widgets = {
            'Habilidades': forms.CheckboxSelectMultiple()
        }
        
class HabilidadForm(forms.ModelForm):
    """Formulario para crear nuevas habilidades"""
    
    class Meta:
        model = Habilidades
        fields = ('habilidad',)
        widgets = {
            'habilidad': forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese la habilidad',
                    'class': 'form-control'
                }
            )
        }
    
    def clean_habilidad(self):
        habilidad = self.cleaned_data['habilidad']
        # Validar que no exista una habilidad con el mismo nombre
        if Habilidades.objects.filter(habilidad__iexact=habilidad).exists():
            raise forms.ValidationError('Esta habilidad ya existe')
        return habilidad

DJDevAlan/applications/Persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import(
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)
from django.db.models import Q
from .models import Empleado, Habilidades
from .forms import EmpleadoForm, HabilidadForm
import os
from django.http import HttpResponse

def debug_view(request):
    return HttpResponse(str(os.listdir('/opt/render/project/src/DJDevAlan')))

class InicioView(TemplateView):
    """Vista de carga página de inicio"""
    template_name='inicio.html'
    
class ListaEmpleadosAdmin(ListView):
    template_name='persona/lista_empleados.html'
    paginate_by= 10
    ordering='first_name'
    context_object_name='empleados'
    model=Empleado

class LisAllEmpleados(ListView):
    template_name = 'persona/lis_all.html' 
    paginate_by = 4
    ordering = 'first_name'
    context_object_name='empleados'
    
    def get_queryset(self):
        palabra_clave=self.request.GET.get("kword", '')
        #print('===================', palabra_clave)
        lista = Empleado.objects.filter(
            Q(first_name__icontains=palabra_clave) |
            Q(last_name__icontains=palabra_clave)
        )
        return lista


class ListByAreaEmpleado(ListView):
    template_name='persona/list_by_area.html'
    context_object_name='empleados'
    
    def get_queryset(self):
        area=self.kwargs['subnombre']
        lista=Empleado.objects.filter(
        departamento__subnombre=area
        )
        return lista
    
class ListHabilidadesEmpleado(ListView):
    template_name='persona/habilidades.html'
    context_object_name='habilidades'
    
    def get_queryset(self):
        empleado=Empleado.objects.get(id=2)
        return empleado.Habilidades.all()


    
class listEmpleadoByKword(ListView):
    template_name='persona/by_kword.html'
    context_object_name='empleados'
    
    def get_queryset(self):
        print('*********************')
        palabra_clave=self.request.GET.get("kword", '')
        #print('===================', palabra_clave)
        lista=Empleado.objects.filter(first_name=palabra_clave)
        return lista
    

class EmpleadosDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"
    
    def get_context_data(self, **kwargs):
        context = super(EmpleadosDetailView, self).get_context_data(**kwargs)
        context["titulo"]='Empleado del mes'
        return context
    

class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    form_class= EmpleadoForm
    success_url=reverse_lazy('persona_app:empleados_admin')
    
    def form_valid(self, form):
        empleado=form.save(commit=False)
        empleado.full_name=empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class SuccessView(TemplateView):
    template_name = "persona/success.html"
    
class EmpleadoUpdateView(UpdateView):
    template_name='persona/update.html'
    model=Empleado
    fields=[
        'first_name',
        'last_name',
        'full_name',
        'job',
        'departamento',
        'Habilidades'
    ]
    success_url=reverse_lazy('persona_app:correcto')
    
    def post(self, request, *args, **kwargs):
        self.object=self.get_object()
        print('######################### TODO POST ########################3')
        print(request.POST)
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        self.object=form.save()
        return super(EmpleadoUpdateView, self).form_valid(form)

class EmpleadoDeleteView(DeleteView):
    model=Empleado
    template_name='persona/delete.html'
    success_url=reverse_lazy('persona_app:empleados_admin')
    
class HabilidadCreateView(CreateView):
    """Vista para crear nuevas habilidades"""
    template_name = 'persona/add_habilidad.html'
    form_class = HabilidadForm
    success_url = reverse_lazy('persona_app:lista_habilidades')
    
    def form_valid(self, form):
        # Opcional: puedes añadir lógica adicional aquí
        return super(HabilidadCreateView, self).form_valid(form)

class ListaHabilidadesView(ListView):
    """Vista para listar todas las habilidades"""
    template_name = 'persona/lista_habilidades.html'
    model = Habilidades
    context_object_name = 'habilidades'
    ordering = 'habilidad'
    paginate_by = 10

class HabilidadUpdateView(UpdateView):
    """Vista para actualizar habilidades"""
    template_name = 'persona/update_habilidad.html'
    model = Habilidades
    fields = ['habilidad']
    success_url = reverse_lazy('persona_app:lista_habilidades')

class HabilidadDeleteView(DeleteView):
    """Vista para eliminar habilidades"""
    model = Habilidades
    template_name = 'persona/delete_habilidad.html'
    success_url = reverse_lazy('persona_app:lista_habilidades')
    

DJDevAlan/templates/persona/add.html
{% extends 'base.html' %}

{% block title %}
    Registrar Empleado Nuevo
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Persona</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{%csrf_token%}
            <div class="medium-6 cell">
                <label>Nombres
                    {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos
                    {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo
                    {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Habilidades
                    {{form.Habilidades}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Foto:
                    {{form.avatar}}
                </label>
            </div>
            <button type="submit" class="button success">Agregar</button>
        </form>
    </div>
</div>
{% endblock content %}

DJDevAlan/templates/persona/add_habilidad.html
{% extends 'base.html' %}

{% block title %}
    Registrar Nueva Habilidad
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Registrar Nueva Habilidad</h1>
        </div>
        
        <div class="cell">
            <div class="callout">
                <p>Ingrese el nombre de la nueva habilidad. Asegúrese de que no exista previamente en el sistema.</p>
            </div>
        </div>
        
        <div class="cell">
            <form method="POST">{% csrf_token %}
                <div class="grid-x grid-margin-x">
                    <div class="medium-6 cell">
                        <label>
                            Nombre de la Habilidad
                            {{ form.habilidad }}
                        </label>
                        {% if form.habilidad.errors %}
                            <div class="callout alert">
                                {{ form.habilidad.errors }}
                            </div>
                        {% endif %}
                    </div>
                    
                    <div class="cell">
                        <button type="submit" class="button success">
                            <i class="fi-save"></i> Guardar Habilidad
                        </button>
                        
                        <a href="{% url 'persona_app:lista_habilidades' %}" class="button secondary">
                            <i class="fi-list"></i> Ver Todas las Habilidades
                        </a>
                        
                        <a href="{% url 'persona_app:inicio' %}" class="button warning">
                            <i class="fi-home"></i> Ir al Inicio
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

DJDevAlan/templates/persona/by_kword.html
<h1>Buscar Empleados por palabra</h1>

<form action="" method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese el nombre aqui">
    <button type="submit">Buscar</button>
    
    <h3>Lista de resultados </h3>
    <ul>
        {% for e in empleados %}
            <li>{{e}}</li>
        {% endfor %}
    </ul>
</form>

DJDevAlan/templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar Empleado
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Eliminar Empleado: {{object.first_name}} {{object.last_name}}</h1>
            <form action="" method="post">{% csrf_token %}
                <div class="callout secondary">
                <p>Confirme que desea eliminar</p>
                <button type="submit" class="alert button">Confirmar</button>
                                    
                </div>
            </form>
        </div>
    </div>
{% endblock content %}
    

DJDevAlan/templates/persona/delete_habilidad.html
{% extends 'base.html' %}

{% block title %}
    Eliminar Habilidad
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Eliminar Habilidad</h1>
        </div>
        
        <div class="cell">
            <div class="callout alert">
                <h5>¿Está seguro que desea eliminar esta habilidad?</h5>
                <p><strong>{{ object.habilidad }}</strong></p>
                <p>Esta acción no se puede deshacer.</p>
            </div>
        </div>
        
        <div class="cell">
            <form method="POST">{% csrf_token %}
                <button type="submit" class="button alert">
                    <i class="fi-trash"></i> Confirmar Eliminación
                </button>
                
                <a href="{% url 'persona_app:lista_habilidades' %}" class="button secondary">
                    <i class="fi-x"></i> Cancelar
                </a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

DJDevAlan/templates/persona/detail_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{object.full_name}}{% endblock %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center" >
            <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
                <div class="card-divider">
                    {{empleado.get_job_display}}
                </div>

                {% if empleado.avatar %}
                    <img src="{{empleado.avatar.url}}" alt="" style="width: 100%; height: auto;">
                {% else %}
                    <img src="{% static 'img/ima1.jpg' %}"style="width: 100%; height: auto;">
                {% endif %}
                <div class="card-section">
                    <h4>{{empleado.first_name}}</h4>
                    <p>{{empleado.last_name}}</p>
                    <p>{{empleado.departamento.subnombre}}</p>
                    <p><span class="label">Habilidades:</span></p>
                    <ul class="vertical menu">
                        {% for h in empleado.Habilidades.all  %}
                            <li>{{h.habilidad}}</li>
                        {% endfor %} 
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

DJDevAlan/templates/persona/habilidades.html
<h1>Habilidades de Empleado</h1>

<ul>
    {%for h in habilidades%}
        <li>
            {{h}}
        </li>
    {%endfor%}
</ul>

DJDevAlan/templates/persona/lis_all.html
{% extends 'base.html' %}

{% block content %}

    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Empleados</h1>
            <form class="cell grid-x grid-margin-x" method="get">{% csrf_token %}

                <div class="cell large-7">
                    <input type="text" id="kword" name="kword" placeholder="bucar empleado">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="success button">Buscar</button>
                </div>
            </form>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="150">ID</th>
                            <th width="150">NOMBRES</th>
                            <th width="150">APELLIDOS </th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for empleado in empleados %}
                        <tr>
                            <td>{{empleado.id}}</td>
                            <td>{{empleado.first_name}}</td>
                            <td>{{empleado.last_name}}</td>
                            <td>{{empleado.departamento}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' empleado.pk %}">Ver</a></td>
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                        {% endif %}

                        
                        {% for pagina in paginator.page_range  %}
                            {% if pagina == page_obj.number %}
                            <li class="current"><span class="show-for-sr">You´re on page</span>{{pagina}}</li>
                            {% else %}
                            <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                            {% endif %}
                        {% endfor %}
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}">siguiente</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

DJDevAlan/templates/persona/list_all.html
<h1>Lista de todos los empleados</h1>

<ul>
    {%forein object-list%}
        <li>
            {{e}}
        </li>
    {%endfor%}
</ul>

DJDevAlan/templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    Lista de todos los empleados
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por area:</div>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="150">ID</th>
                            <th width="150">NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for empleado in empleados %}
                            <tr>
                                <td>{{empleado.id}}</td>
                                <td>{{empleado.first_name}}</td>
                                <td>{{empleado.last_name}}</td>
                                <td>{{empleado.departamento}}</td>
                                <td><a href="{% url 'persona_app:empleado_detail' empleado.id %}" class="button warning">Ver</a></td>
                            </tr>
                        {% endfor %}
                            
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{%endblock content %}

DJDevAlan/templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block content %}

    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Empleados</h1>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="150">ID</th>
                            <th width="150">NOMBRES</th>
                            <th width="150">APELLIDOS </th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for empleado in empleados %}
                        <tr>
                            <td>{{empleado.id}}</td>
                            <td>{{empleado.first_name}}</td>
                            <td>{{empleado.last_name}}</td>
                            <td>{{empleado.departamento}}</td>
                            <td>
                                <a class="button success" href="{% url 'persona_app:Modificar_empleado' empleado.id %}">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'persona_app:Eliminar_Empleado' empleado.id %}" class="button alert">Eliminar</a>
                            </td>
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                        {% endif %}

                        
                        {% for pagina in paginator.page_range  %}
                            {% if pagina == page_obj.number %}
                            <li class="current"><span class="show-for-sr">You´re on page</span>{{pagina}}</li>
                            {% else %}
                            <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                            {% endif %}
                        {% endfor %}
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}">siguiente</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

DJDevAlan/templates/persona/lista_habilidades.html
{% extends 'base.html' %}

{% block title %}
    Lista de Habilidades
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Lista de Habilidades</h1>
        </div>
        
        <div class="cell">
            <div class="button-group">
                <a href="{% url 'persona_app:add_habilidad' %}" class="button success">
                    <i class="fi-plus"></i> Agregar Nueva Habilidad
                </a>
                <a href="{% url 'persona_app:inicio' %}" class="button warning">
                    <i class="fi-home"></i> Ir al Inicio
                </a>
            </div>
        </div>
        
        <div class="cell">
            <div class="callout">
                <h5>Total de Habilidades: {{ habilidades.count }}</h5>
            </div>
        </div>
        
        <div class="cell">
            <table class="hover">
                <thead>
                    <tr>
                        <th width="50">ID</th>
                        <th>Nombre de la Habilidad</th>
                        <th width="200">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for habilidad in habilidades %}
                    <tr>
                        <td>{{ habilidad.id }}</td>
                        <td>{{ habilidad.habilidad }}</td>
                        <td>
                            <a href="{% url 'persona_app:update_habilidad' habilidad.id %}" 
                               class="button tiny warning">
                                <i class="fi-pencil"></i> Editar
                            </a>
                            <a href="{% url 'persona_app:delete_habilidad' habilidad.id %}" 
                               class="button tiny alert">
                                <i class="fi-trash"></i> Eliminar
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3" class="text-center">
                            <div class="callout secondary">
                                No hay habilidades registradas aún.
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
        <!-- Paginación -->
        {% if is_paginated %}
        <div class="cell">
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}">Atrás</a>
                    </li>
                    {% endif %}
                    
                    {% for pagina in paginator.page_range %}
                    <li class="{% if page_obj.number == pagina %}current{% endif %}">
                        <a href="?page={{ pagina }}">{{ pagina }}</a>
                    </li>
                    {% endfor %}
                    
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

DJDevAlan/templates/persona/update.html
{% extends 'base.html' %}

{% block title %}
    Edita Empleado
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>

        <div class="cell">
            <form class="grid-x" method="POST">
                {% csrf_token %}

                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Trabajo:
                        {{ form.job }}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Area:
                        {{ form.departamento }}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Habilidades extras:
                        {{ form.Habilidades }}
                    </label>
                </div>

                <div class="cell">
                    <button type="submit" class="success button">
                        Guardar
                    </button>
                </div>

            </form>
        </div>
    </div>
</div>

{% endblock content %}

DJDevAlan/templates/persona/update_habilidad.html
{% extends 'base.html' %}

{% block title %}
    Editar Habilidad
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Editar Habilidad</h1>
        </div>
        
        <div class="cell">
            <form method="POST">{% csrf_token %}
                <div class="grid-x grid-margin-x">
                    <div class="medium-6 cell">
                        <label>
                            Nombre de la Habilidad
                            {{ form.habilidad }}
                        </label>
                    </div>
                    
                    <div class="cell">
                        <button type="submit" class="button success">
                            <i class="fi-save"></i> Guardar Cambios
                        </button>
                        
                        <a href="{% url 'persona_app:lista_habilidades' %}" class="button secondary">
                            <i class="fi-x"></i> Cancelar
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}