DJDevAlan/applications/Persona/urls.py
from django.urls import path
from . import views

app_name="persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(),
        name='inicio'
    ),
    path('Listar-todos-empleados/', views.LisAllEmpleados.as_view(), name='empleados_all'),
    path('lista-by-area/<subnombre>/', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('buscar-empleado/', views.listEmpleadoByKword.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadosDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'success/', 
        views.SuccessView.as_view(), 
        name='correcto'
    ),
    path(
        'update-empleado/<pk>', 
        views.EmpleadoUpdateView.as_view(), 
        name='Modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>', 
        views.EmpleadoDeleteView.as_view(), 
        name='Eliminar_Empleado'
    ),
    path(
        'lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(), 
        name='empleados_admin'
    ),
    path('habilidades/', views.ListaHabilidadesView.as_view(), name='lista_habilidades'),
    path('habilidad/add/', views.HabilidadCreateView.as_view(), name='add_habilidad'),
    path('habilidad/update/<pk>/', views.HabilidadUpdateView.as_view(), name='update_habilidad'),
    path('habilidad/delete/<pk>/', views.HabilidadDeleteView.as_view(), name='delete_habilidad'),
    
]

DJDevAlan/applications/departamento/urls.py
from django.contrib import admin 
from django.urls import path

from . import views
app_name='departamento_app'

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path('departamento-lista/',views.DepartamentoListView.as_view(), name='departamento-list'),
]

DJDevAlan/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.Persona.views import LisAllEmpleados
from django.conf.urls.static import static
from django.conf import settings
from applications.Persona.views import debug_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.Persona.urls')),
    path('', include('applications.departamento.urls')),
    path('', debug_view), 
    #path('listar-todos-empleados/', LisAllEmpleados.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DJDevAlan/applications/departamento/models.py
from django.db import models


class Departamento(models.Model):
    nombre=models.TextField('Nombre',max_length=50)
    subnombre=models.TextField('Nombre_corto',max_length=30)
    activo = models.BooleanField('Anulado', default='False')
    

    class Meta:
        verbose_name='Mi Departamento'
        verbose_name_plural='Areas de la empresa'
        ordering=['-nombre']
        unique_together=('nombre','subnombre')
    
    def __str__(self):
        return self.nombre + ' - ' + self.subnombre
    

DJDevAlan/applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    departamento = forms.CharField(max_length=50)
    short_name = forms.CharField(max_length=50)

DJDevAlan/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView

from .models import Departamento
from applications.Persona.models import Empleado
from .forms import NewDepartamentoForm
from django.views.generic import (ListView)


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name='departamentos'


class NewDepartamentoView(FormView):
    template_name = "departamento/new_departamento.html"
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        depa = Departamento(
            nombre=form.cleaned_data['departamento'],
            subnombre=form.cleaned_data['short_name']
        )
        depa.save()

        #nombre = form.cleaned_data['nombre']
        #apellido = form.cleaned_data['apellidos']

        Empleado.objects.create(
            #first_name=nombre,
            #last_name=apellido,
            job='1',
            departamento=depa
        )

        return super().form_valid(form)

    def form_invalid(self, form):
        print("ERRORES:", form.errors)
        return super().form_invalid(form)



# Create your views here.

DJDevAlan/templates/departamento/lista.html
{% extends 'base.html' %}

{% block title %}
    Lista departamentos
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista de Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{ departamento.nombre }}</td>
                            <td>{{ departamento.subnombre }}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.subnombre %}">Ver Empleados</a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="3">No hay departamentos registrados</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

DJDevAlan/templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block title %}
    Registrar Departamento
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Regitrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombre del Departamento:
                    {{form.departamento}}
                </label>
            </div>

            <div class="medium-6 cell">
                <label>Nombre corto:
                    {{form.short_name}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button">Guardar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}